import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import fetcher from "../lib/fetcher";
import {OauthUrlResponse} from "./models/OauthUrlResponse";
import React from "react";

export default function Home() {
    const { data, error } = useSWR<OauthUrlResponse>('/api/mal/oauth-url', fetcher)

    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Anime Tier List
        </h1>

          {!!data && !error ? (
              <div className={styles.grid}>
                  <a href={data.oauthUrl} className={styles.card}>
                      <h2>Login &rarr;</h2>
                      <p>Login to MyAnimeList to get started</p>
                  </a>
              </div>
          ) : null}
      </main>
    </div>
  )
}
