import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from "react";
import {useOauthUrl} from "../hooks/useOauthUrl";

export default function Home() {
    const oauthUrl = useOauthUrl()

    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Anime Tier List
        </h1>

          {!!oauthUrl ? (
              <div className={styles.grid}>
                  <a href={oauthUrl.url} className={styles.card}>
                      <h2>Login &rarr;</h2>
                      <p>Login to MyAnimeList to get started</p>
                  </a>
              </div>
          ) : null}
      </main>
    </div>
  )
}
